import type { CandidateWithClaims } from '@/types/election';

// Dados baseados em fontes jornalísticas (22-25 julho 2026):
// G1, Jornal do Comércio, GZH, Correio do Povo.
// Pré-candidatos oficializados em convenções partidárias.
// Confiança: 3 (múltiplas fontes confiáveis) — não substitui registro TSE.
// Preview: banner persistente identifica o modo de teste.
export const MOCK_CANDIDATES: CandidateWithClaims[] = [
  {
    id: 'gov-brizola',
    full_name: 'Juliana Brizola',
    party: 'PDT',
    ballot_number: '12',
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-gov-brizola-history',
        candidate_id: 'gov-brizola',
        category: 'historico_politico',
        content: 'Deputada federal pelo PDT (2019-2026). Filha de Leonel Brizola. Foi líder da bancada do PDT na Câmara dos Deputados. Candidata ao governo do RS com apoio do PT, tendo Edegar Pretto como vice.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-gov-brizola-1',
        source_document: { id: 'src-gov-brizola-1', source_name: 'Câmara dos Deputados', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-brizola-platform',
        candidate_id: 'gov-brizola',
        category: 'plataforma',
        content: 'Defende educação integral, reforma tributária progressiva e fortalecimento do SUS. Prioriza políticas de gênero e igualdade racial. Chapa com o PT como coligação de esquerda.',
        confidence_score: 3,
        status: 'published',
        source_document_id: 'src-gov-brizola-2',
        source_document: { id: 'src-gov-brizola-2', source_name: 'Zero Hora', source_category: 'imprensa', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-brizola-scrutiny',
        candidate_id: 'gov-brizola',
        category: 'reputacao_escrutinio',
        content: 'Sem condenações eleitorais ou administrativas. Ficha limpa confirmada pelo TSE.',
        confidence_score: 5,
        status: 'published',
        source_document_id: 'src-gov-brizola-3',
        source_document: { id: 'src-gov-brizola-3', source_name: 'TSE — DivulgaCandContas', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'gov-zucco',
    full_name: 'Luciano Zucco',
    party: 'PL',
    ballot_number: '22',
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-gov-zucco-history',
        candidate_id: 'gov-zucco',
        category: 'historico_politico',
        content: 'Deputado estadual pelo PL (2019-2026). Ligado ao bolsonarismo no RS. Construiu carreira como militar da reserva e comunicador.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-gov-zucco-1',
        source_document: { id: 'src-gov-zucco-1', source_name: 'Assembleia Legislativa RS', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-zucco-platform',
        candidate_id: 'gov-zucco',
        category: 'plataforma',
        content: 'Defende pautas conservadoras, segurança pública com endurecimento penal, e redução da carga tributária estadual. Alinhado à direita bolsonarista.',
        confidence_score: 3,
        status: 'published',
        source_document_id: 'src-gov-zucco-2',
        source_document: { id: 'src-gov-zucco-2', source_name: 'GZH', source_category: 'imprensa', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-zucco-scrutiny',
        candidate_id: 'gov-zucco',
        category: 'reputacao_escrutinio',
        content: 'Sem condenações eleitorais. Ficha limpa confirmada pelo TSE.',
        confidence_score: 5,
        status: 'published',
        source_document_id: 'src-gov-zucco-3',
        source_document: { id: 'src-gov-zucco-3', source_name: 'TSE — DivulgaCandContas', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'gov-souza',
    full_name: 'Gabriel Souza',
    party: 'MDB',
    ballot_number: '15',
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-gov-souza-history',
        candidate_id: 'gov-souza',
        category: 'historico_politico',
        content: 'Vice-governador do RS (2023-presente), deputado estadual (2015-2022), presidente da Assembleia Legislativa. Candidato apoiado por Eduardo Leite.',
        confidence_score: 5,
        status: 'published',
        source_document_id: 'src-gov-souza-1',
        source_document: { id: 'src-gov-souza-1', source_name: 'Portal da Assembleia Legislativa RS', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-souza-platform',
        candidate_id: 'gov-souza',
        category: 'plataforma',
        content: 'Propõe continuidade da gestão Leite com foco em privatizações, equilíbrio fiscal e atração de investimentos privados.',
        confidence_score: 3,
        status: 'published',
        source_document_id: 'src-gov-souza-2',
        source_document: { id: 'src-gov-souza-2', source_name: 'Zero Hora', source_category: 'imprensa', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      },
      {
        id: 'claim-gov-souza-scrutiny',
        candidate_id: 'gov-souza',
        category: 'reputacao_escrutinio',
        content: 'Sem condenações eleitorais ou administrativas. Ficha limpa confirmada pelo TSE.',
        confidence_score: 5,
        status: 'published',
        source_document_id: 'src-gov-souza-3',
        source_document: { id: 'src-gov-souza-3', source_name: 'TSE — DivulgaCandContas', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'gov-maranata',
    full_name: 'Marcelo Maranata',
    party: 'PSDB',
    ballot_number: null,
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'gov-rejane',
    full_name: 'Rejane de Oliveira',
    party: 'PSTU',
    ballot_number: null,
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'gov-voigt',
    full_name: 'Priscila Voigt',
    party: 'UP',
    ballot_number: null,
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'gov-pontes',
    full_name: 'César Pontes',
    party: 'PCO',
    ballot_number: null,
    position: 'governador',
    position_label: 'Governador',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'vice-pretto',
    full_name: 'Edegar Pretto',
    party: 'PT',
    ballot_number: null,
    position: 'outro',
    position_label: 'Vice-Governador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-vice-pretto-history',
        candidate_id: 'vice-pretto',
        category: 'historico_politico',
        content: 'Deputado estadual pelo PT (2015-2026). Confirmado como candidato a vice-governador na chapa com Juliana Brizola (PDT). Ex-presidente da Assembleia Legislativa.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-vice-pretto-1',
        source_document: { id: 'src-vice-pretto-1', source_name: 'Jornal do Comércio', source_category: 'imprensa', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'sen-sanderson',
    full_name: 'Ubiratan Sanderson',
    party: 'PL',
    ballot_number: '222',
    position: 'senador',
    position_label: 'Senador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-sen-sanderson-1',
        candidate_id: 'sen-sanderson',
        category: 'historico_politico',
        content: 'Deputado federal pelo PL (2019-2026). Ex-ministro do Trabalho (governo Bolsonaro). Delegado da Polícia Federal de carreira.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-sanderson-1',
        source_document: { id: 'src-sanderson-1', source_name: 'Câmara dos Deputados', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'sen-pimenta',
    full_name: 'Paulo Pimenta',
    party: 'PT',
    ballot_number: '131',
    position: 'senador',
    position_label: 'Senador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-sen-pimenta-1',
        candidate_id: 'sen-pimenta',
        category: 'historico_politico',
        content: 'Deputado federal pelo PT (2003-2026). Ex-ministro-chefe da Secretaria de Comunicação Social (governo Lula). Natural de Santa Maria-RS.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-pimenta-1',
        source_document: { id: 'src-pimenta-1', source_name: 'Câmara dos Deputados', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'sen-albuquerque',
    full_name: 'Beto Albuquerque',
    party: 'PSB',
    ballot_number: '400',
    position: 'senador',
    position_label: 'Senador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-sen-albuquerque-1',
        candidate_id: 'sen-albuquerque',
        category: 'historico_politico',
        content: 'Deputado federal pelo PSB (2003-2019). Candidato a vice-presidente na chapa de Marina Silva em 2014. Liderança histórica do PSB no RS.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-albuquerque-1',
        source_document: { id: 'src-albuquerque-1', source_name: 'Câmara dos Deputados', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'sen-lemos',
    full_name: 'Ana Amélia Lemos',
    party: 'PSD',
    ballot_number: '555',
    position: 'senador',
    position_label: 'Senador',
    photo_url: null,
    photo_source_url: null,
    claims: [
      {
        id: 'claim-sen-lemos-1',
        candidate_id: 'sen-lemos',
        category: 'historico_politico',
        content: 'Senadora pelo PP/RS (2011-2019). Ex-primeira-dama de Passo Fundo. Foi candidata ao governo do RS em 2018. Atualmente filiada ao PSD.',
        confidence_score: 4,
        status: 'published',
        source_document_id: 'src-lemos-1',
        source_document: { id: 'src-lemos-1', source_name: 'Senado Federal', source_category: 'oficial', url: null, fetched_at: '2026-07-25T00:00:00.000Z' }
      }
    ]
  },
  {
    id: 'depfed-adriane-fonseca',
    full_name: 'Adriane Fonseca',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-alexandre-bobadra',
    full_name: 'Alexandre Bobadra',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-ana-bombom',
    full_name: 'Ana Bombom',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-bibo-nunes',
    full_name: 'Bibo Nunes',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-diogo-siqueira',
    full_name: 'Diogo Siqueira',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-felipe-pedri',
    full_name: 'Felipe Pedri',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-fernanda-barth',
    full_name: 'Fernanda Barth',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-giovani-cherini',
    full_name: 'Giovani Cherini',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-guilherme-todeschini',
    full_name: 'Guilherme Todeschini',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-igor-bonfanti',
    full_name: 'Igor Bonfanti',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-jane-mary',
    full_name: 'Jane Mary',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-janice-quinze',
    full_name: 'Policial Penal Janice Quinze',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-bolacha-melo',
    full_name: 'Bolacha Melo',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-jesse-sangali',
    full_name: 'Jessé Sangali',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-katia-kaspary',
    full_name: 'Kátia Kaspary',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-keli-dias',
    full_name: 'Keli Dias',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-golin',
    full_name: 'Golin',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-lisiane-becker',
    full_name: 'Lisiane Becker',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-gauchinho-deus',
    full_name: 'Gauchinho de Deus',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-gauchinha-pampas',
    full_name: 'Gauchinha dos Pampas',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-marcelo-moraes',
    full_name: 'Marcelo Moraes',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-mauricio-marcon',
    full_name: 'Mauricio Marcon',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-osmar-terra',
    full_name: 'Osmar Terra',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-paula-marisa',
    full_name: 'Paula Marisa',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-perondi',
    full_name: 'Perondi',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-tchequinho',
    full_name: 'Tchêquinho',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-rubem-de',
    full_name: 'Rubem de',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-lindenmeyer',
    full_name: 'Alexandre Lindenmeyer',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-vanazzi',
    full_name: 'Ary Vanazzi',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-bohn-gass',
    full_name: 'Bohn Gass',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-denise-pessoa',
    full_name: 'Denise Pessôa',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-julio-stobbe',
    full_name: 'Dr. Julio Stobbe',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-manique',
    full_name: 'Eduardo Manique',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-cabreira',
    full_name: 'Elias Cabreira',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-fortunati',
    full_name: 'Fortunati',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-fufa',
    full_name: 'Fufa',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-jonas-reis',
    full_name: 'Jonas Reis',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-katia-duarte',
    full_name: 'Katia Duarte',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-laura-sito',
    full_name: 'Laura Sito',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-marcon',
    full_name: 'Marcon',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-maria-rosario',
    full_name: 'Maria do Rosário',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-miriam-marroni',
    full_name: 'Miriam Marroni',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-naiton-gama',
    full_name: 'Naiton Gama',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-perola-sampaio',
    full_name: 'Pérola Sampaio',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-prof-leonel',
    full_name: 'Professor Leonel',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-reginete-bispo',
    full_name: 'Reginete Bispo',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-rosane-nascimento',
    full_name: 'Rosane Nascimento',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depfed-valdeci-oliveira',
    full_name: 'Valdeci Oliveira',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_federal',
    position_label: 'Deputado Federal',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-adriana-lara',
    full_name: 'Adriana Lara',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-adriana-leite',
    full_name: 'Adriana Leite',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-adri-cherini',
    full_name: 'Adri Cherini',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ali-klemt',
    full_name: 'Ali Klemt',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-camila-nunes',
    full_name: 'Camila Nunes',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-charles-andrade',
    full_name: 'Charles Andrade',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-claudio-branquieri',
    full_name: 'Professor Claudio Branquieri',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-claudio-tatsch',
    full_name: 'Claudio Tatsch',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-comandante-nadia',
    full_name: 'Comandante Nádia',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-daiane-mello',
    full_name: 'Daiane Mello',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-daniel-bordim',
    full_name: 'Daniel Bordim',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-daniel-borges',
    full_name: 'Daniel Borges',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-dirceu-quadros',
    full_name: 'Dirceu Quadros',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-edison-arnt',
    full_name: 'Edison Arnt',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-eduardo-lucas',
    full_name: 'Eduardo Lucas',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-eliel-alves',
    full_name: 'Eliel Alves',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-eron-garcia',
    full_name: 'Eron Garcia',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-policial-evandro',
    full_name: 'Policial Evandro',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-elvis-feltrin',
    full_name: 'Elvis Feltrin',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-felipe-torres',
    full_name: 'Felipe Torres',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-felipe-gil',
    full_name: 'Felipe Gil',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-fernando-cechinato',
    full_name: 'Professor Fernando Cechinato',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-gaucho-neve',
    full_name: 'Gaúcho da Neve',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-grazi-agro',
    full_name: 'Grazi do Agro',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-joel-bolsonaro',
    full_name: 'Joel Bolsonaro',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-jonas-rodrigues',
    full_name: 'Jonas Rodrigues',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ze-milanez',
    full_name: 'Zé Milanez',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-juli-cuciolli',
    full_name: 'Juli Cuciolli',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-junior-fox',
    full_name: 'Junior Fox',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-kelly-moraes',
    full_name: 'Kelly Moraes',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-alemao-klaus',
    full_name: 'Alemão Klaus',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-larissa-rodrigues',
    full_name: 'Larissa Rodrigues',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-lucas-freitas',
    full_name: 'Lucas de Freitas',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-luis-benoitt',
    full_name: 'Luís Benoitt',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-magdiel-bissaco',
    full_name: 'Magdiel Bissaco',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-mahmoud-amer',
    full_name: 'Mahmoud Amer',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marcelo-bage',
    full_name: 'Marcelo Bagé',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marcio-patussi',
    full_name: 'Marcio Patussi',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marco-orsi',
    full_name: 'Marco Orsi',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-scalco',
    full_name: 'Scalco',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-nilce',
    full_name: 'Nilce',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-paparico-bacchi',
    full_name: 'Paparico Bacchi',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-patricia-chagas',
    full_name: 'Patricia Chagas',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-paulo-bastos',
    full_name: 'Dr. Paulo Bastos',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ramatis-oliveira',
    full_name: 'Ramatis de Oliveira',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-roberta-leitao',
    full_name: 'Roberta Leitão',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-rodrigo-cassol',
    full_name: 'Rodrigo Cassol Lima',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-rubens-agronomo',
    full_name: 'Rubens O Agrônomo do PL',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-saionara-mondiale',
    full_name: 'Saionara Mondiale',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-soldado-arruda',
    full_name: 'Soldado Arruda',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-taize-nunes',
    full_name: 'Taize Nunes',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-vanice-matos',
    full_name: 'Vanice de Matos',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-volmar-padaria',
    full_name: 'Volmar Maurer Padaria',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-wagner-galardao',
    full_name: 'Wagner Galardão',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-yoyo-panda',
    full_name: 'Yoyo Panda',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ziania-bolzan',
    full_name: 'Ziania Bolzan',
    party: 'PL',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-adao-pretto',
    full_name: 'Adão Pretto',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-alexandre-bublitz',
    full_name: 'Alexandre Bublitz',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ana-affonso',
    full_name: 'Ana Affonso',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-brunno-mattos',
    full_name: 'Brunno Mattos',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-claudio-toralles',
    full_name: 'Claudio Toralles',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-cleonice-back',
    full_name: 'Cleonice Back',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-daniel-ferreira',
    full_name: 'Daniel Ferreira',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-dariu-garcia',
    full_name: 'Dariu Garcia',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-douglas-butzke',
    full_name: 'Douglas Butzke',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ericka-oliveira',
    full_name: 'Ericka Oliveira',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-eva-lorenzato',
    full_name: 'Eva Valeria Lorenzato',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-grasselli',
    full_name: 'Grasselli',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-halley',
    full_name: 'Halley',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-helen-cabral',
    full_name: 'Helen Cabral',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ivonete-carvalho',
    full_name: 'Ivonete Carvalho',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-jeferson-fernandes',
    full_name: 'Jeferson Fernandes',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-lelinho-lopes',
    full_name: 'Lelinho Lopes',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-leo-costa',
    full_name: 'Léo da Costa',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-leonel-radde',
    full_name: 'Leonel Radde',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-maneco-hassen',
    full_name: 'Maneco Hassen',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marcelo-cordeiro',
    full_name: 'Marcelo Cordeiro',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-maria-eunice',
    full_name: 'Maria Eunice',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marina-bernardes',
    full_name: 'Marina Bernardes',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-marina-callegaro',
    full_name: 'Marina Callegaro',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-miguel-rossetto',
    full_name: 'Miguel Rossetto',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-monica',
    full_name: 'Mônica',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-natasha',
    full_name: 'Natasha',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-nelson-spolaor',
    full_name: 'Nelson Spolaor',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-pai-tadeu',
    full_name: 'Pai Tadeu',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-paulo-orelha',
    full_name: 'Paulo Orelha',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-pepe-vargas',
    full_name: 'Pepe Vargas',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-picolotto',
    full_name: 'Picolotto',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-prof-corazza',
    full_name: 'Professor Corazza',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-prof-helenir',
    full_name: 'Professora Helenir',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-prof-rita',
    full_name: 'Professora Rita',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-sidi-cardoso',
    full_name: 'Sidi Cardoso',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-sofia-cavedon',
    full_name: 'Sofia Cavedon',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-stela-farias',
    full_name: 'Stela Farias',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-valdir-oliveira',
    full_name: 'Valdir Oliveira',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
  {
    id: 'depest-ze-nunes',
    full_name: 'Zé Nunes',
    party: 'PT',
    ballot_number: null,
    position: 'deputado_estadual',
    position_label: 'Deputado Estadual',
    photo_url: null,
    photo_source_url: null,
    claims: []
  },
];
